# Generated by Django 2.2.1 on 2019-08-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='', max_length=100, verbose_name='部署名称')),
                ('record_id', models.CharField(default='', max_length=100, verbose_name='本次记录')),
                ('alias', models.CharField(default='', max_length=100, verbose_name='别名')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='关联项目')),
                ('server_ids', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='关联主机')),
                ('target_root', models.CharField(default='', max_length=200, verbose_name='部署路径')),
                ('target_releases', models.CharField(default='', max_length=200, verbose_name='目标仓库')),
                ('prev_record', models.CharField(default='', max_length=100, verbose_name='前次记录')),
                ('is_rollback', models.BooleanField(default=False, verbose_name='可否回滚')),
            ],
            options={
                'verbose_name': '部署记录',
                'verbose_name_plural': '部署记录',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='', max_length=100, verbose_name='项目名称')),
                ('alias', models.CharField(default='', max_length=100, verbose_name='描叙')),
                ('project_type', models.CharField(default='', max_length=30, verbose_name='项目类型')),
                ('repo_mode', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='项目子类型')),
                ('owner', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='所有者')),
                ('apk_path', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='apk文件路径')),
                ('ui_capabilities', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ui自动化基础启动参数')),
                ('user_id', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='关联用户id')),
            ],
            options={
                'verbose_name': '项目配置',
                'verbose_name_plural': '项目配置',
            },
        ),
    ]
