# Generated by Django 2.2.1 on 2019-08-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ui_capabilities',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='ui自动化基础启动参数'),
        ),
    ]
