# Generated by Django 2.2.1 on 2019-09-18 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcenter', '0002_auto_20190902_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='test_model',
            new_name='case_model',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='test_setUp',
            new_name='case_setUp',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='test_tearDown',
            new_name='case_tearDown',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='test_title',
            new_name='case_title',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='test_id',
        ),
        migrations.AddField(
            model_name='testcase',
            name='case_type',
            field=models.CharField(default=1, max_length=50, verbose_name='用例类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project', verbose_name='所属项目'),
        ),
    ]
